import path from "node:path";
import ts from "typescript";
import { msBetween, nowIso, type AgentResult } from "@acme/agent-runtime";
import {
  CodeGenInputSchema,
  CodeGenOutputSchema,
  EventEnvelopeSchema,
  GeneratedFileSchema,
  type CodeGenInput,
  type CodeGenOutput,
  type EventEnvelope,
  type FileSpec,
  type GeneratedFile,
  type RecoveryAction,
} from "@acme/contracts";

const AGENT_NAME = "code-gen";
const DEFAULT_OUTPUT_DIR = ".";

type CodeGenErrorCode = "INPUT_INVALID" | "SCOPE_VIOLATION" | "COMPILE_VALIDATION_FAILED" | "GENERATION_FAILED";

class CodeGenError extends Error {
  readonly code: CodeGenErrorCode;

  constructor(code: CodeGenErrorCode, message: string) {
    super(message);
    this.code = code;
  }
}

function normalizeSlashes(value: string): string {
  return value.replaceAll("\\", "/");
}

function isWindowsAbsolutePath(value: string): boolean {
  return /^[A-Za-z]:\//.test(normalizeSlashes(value));
}

function resolveOutputPath(outputDir: string, filePath: string): string {
  const normalizedOutputDir = path.posix.normalize(normalizeSlashes(outputDir.trim() || DEFAULT_OUTPUT_DIR));
  const normalizedFilePath = path.posix.normalize(normalizeSlashes(filePath.trim()));

  if (normalizedOutputDir.length === 0) {
    throw new CodeGenError("INPUT_INVALID", "outputDir cannot be empty");
  }

  if (
    normalizedOutputDir.startsWith("/") ||
    isWindowsAbsolutePath(normalizedOutputDir) ||
    normalizedOutputDir === ".." ||
    normalizedOutputDir.startsWith("../")
  ) {
    throw new CodeGenError(
      "SCOPE_VIOLATION",
      `outputDir must be project-relative and non-escaping: ${outputDir}`,
    );
  }

  if (normalizedFilePath.length === 0) {
    throw new CodeGenError("INPUT_INVALID", "file path cannot be empty");
  }

  if (
    normalizedFilePath.startsWith("/") ||
    isWindowsAbsolutePath(normalizedFilePath) ||
    normalizedFilePath === ".." ||
    normalizedFilePath.startsWith("../")
  ) {
    throw new CodeGenError("SCOPE_VIOLATION", `path is outside outputDir: ${filePath}`);
  }

  const resolvedPath = path.posix.normalize(path.posix.join(normalizedOutputDir, normalizedFilePath));
  if (resolvedPath === ".." || resolvedPath.startsWith("../")) {
    throw new CodeGenError("SCOPE_VIOLATION", `path is outside outputDir: ${filePath}`);
  }

  if (normalizedOutputDir !== ".") {
    if (!(resolvedPath === normalizedOutputDir || resolvedPath.startsWith(`${normalizedOutputDir}/`))) {
      throw new CodeGenError("SCOPE_VIOLATION", `path is outside outputDir: ${filePath}`);
    }
  }

  return resolvedPath;
}

function detectLanguage(filePath: string): string {
  const ext = path.posix.extname(filePath).toLowerCase();
  switch (ext) {
    case ".ts":
      return "typescript";
    case ".tsx":
      return "typescriptreact";
    case ".js":
      return "javascript";
    case ".jsx":
      return "javascriptreact";
    case ".py":
      return "python";
    case ".json":
      return "json";
    case ".md":
      return "markdown";
    case ".sql":
      return "sql";
    case ".yaml":
    case ".yml":
      return "yaml";
    case ".css":
      return "css";
    case ".html":
      return "html";
    case ".sh":
      return "shell";
    default:
      return "plaintext";
  }
}

function toIdentifier(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (normalized.length === 0) return "generated_file";
  if (/^[0-9]/.test(normalized)) return `generated_${normalized}`;
  return normalized;
}

function escapeForStringLiteral(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, " ");
}

function buildTypeScriptContent(spec: FileSpec, outputPath: string, includeTypes: boolean): string {
  const functionName = toIdentifier(path.posix.basename(outputPath, path.posix.extname(outputPath)));
  const summary = escapeForStringLiteral(spec.purpose);
  if (includeTypes) {
    return [
      "/**",
      ` * ${spec.purpose}.`,
      " * Generated by the code-gen agent.",
      " */",
      `export function ${functionName}(): string {`,
      `  return "${summary}";`,
      "}",
      "",
    ].join("\n");
  }

  return [
    "/**",
    ` * ${spec.purpose}.`,
    " * Generated by the code-gen agent.",
    " */",
    `export function ${functionName}() {`,
    `  return "${summary}";`,
    "}",
    "",
  ].join("\n");
}

function buildContent(spec: FileSpec, outputPath: string, language: string): string {
  switch (language) {
    case "typescript":
      return buildTypeScriptContent(spec, outputPath, true);
    case "typescriptreact":
      return buildTypeScriptContent(spec, outputPath, true);
    case "javascript":
      return buildTypeScriptContent(spec, outputPath, false);
    case "javascriptreact":
      return buildTypeScriptContent(spec, outputPath, false);
    case "python": {
      const functionName = toIdentifier(path.posix.basename(outputPath, path.posix.extname(outputPath)));
      const summary = escapeForStringLiteral(spec.purpose);
      return [`"""${spec.purpose}."""`, "", `def ${functionName}():`, `    return "${summary}"`, ""].join("\n");
    }
    case "json":
      return `${JSON.stringify(
        {
          purpose: spec.purpose,
          techStack: spec.techStack,
          templateHints: spec.templateHints ?? [],
          dependencies: spec.dependencies ?? [],
        },
        null,
        2,
      )}\n`;
    case "markdown":
      return [`# ${spec.purpose}`, "", "Generated by the code-gen agent.", ""].join("\n");
    default:
      return `${spec.purpose}\n`;
  }
}

function buildGeneratedFiles(input: CodeGenInput): GeneratedFile[] {
  const outputDir = input.outputDir ?? DEFAULT_OUTPUT_DIR;
  const fileSpecs = input.fileSpecs && input.fileSpecs.length > 0 ? input.fileSpecs : input.fileSpec ? [input.fileSpec] : [];

  if (fileSpecs.length === 0) {
    throw new CodeGenError("INPUT_INVALID", "at least one fileSpec is required");
  }

  return fileSpecs.map((spec) => {
    const resolvedPath = resolveOutputPath(outputDir, spec.path);
    const language = detectLanguage(resolvedPath);
    const content = buildContent(spec, resolvedPath, language);
    return GeneratedFileSchema.parse({
      path: resolvedPath,
      content,
      language,
    });
  });
}

function formatDiagnostic(
  diagnostic: ts.Diagnostic,
  virtualToGeneratedPath: Map<string, string>,
): string {
  const message = ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n");
  if (!diagnostic.file || diagnostic.start === undefined) {
    return `tsc: ${message}`;
  }

  const normalizedVirtualPath = path.normalize(diagnostic.file.fileName);
  const generatedPath = virtualToGeneratedPath.get(normalizedVirtualPath) ?? diagnostic.file.fileName;
  const lineAndChar = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
  return `${generatedPath}:${lineAndChar.line + 1}:${lineAndChar.character + 1} ${message}`;
}

function validateTypeScriptCompilation(generatedFiles: GeneratedFile[]): void {
  const typeScriptFiles = generatedFiles.filter((file) => file.language === "typescript" || file.language === "typescriptreact");
  if (typeScriptFiles.length === 0) {
    return;
  }

  const compilerOptions: ts.CompilerOptions = {
    noEmit: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    strict: true,
    skipLibCheck: true,
    jsx: ts.JsxEmit.ReactJSX,
  };

  const defaultHost = ts.createCompilerHost(compilerOptions, true);
  const virtualContents = new Map<string, { content: string; scriptKind: ts.ScriptKind }>();
  const virtualToGeneratedPath = new Map<string, string>();

  for (const file of typeScriptFiles) {
    const virtualAbsolutePath = path.normalize(path.resolve(process.cwd(), ".factory", "virtual", "code-gen", file.path));
    virtualToGeneratedPath.set(virtualAbsolutePath, file.path);
    virtualContents.set(virtualAbsolutePath, {
      content: file.content,
      scriptKind: file.language === "typescriptreact" ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    });
  }

  const host: ts.CompilerHost = {
    ...defaultHost,
    fileExists: (fileName) => virtualContents.has(path.normalize(fileName)) || defaultHost.fileExists(fileName),
    readFile: (fileName) => {
      const virtual = virtualContents.get(path.normalize(fileName));
      if (virtual) return virtual.content;
      return defaultHost.readFile(fileName);
    },
    getSourceFile: (fileName, languageVersion, onError, shouldCreateNewSourceFile) => {
      const virtual = virtualContents.get(path.normalize(fileName));
      if (virtual) {
        return ts.createSourceFile(fileName, virtual.content, languageVersion, true, virtual.scriptKind);
      }
      return defaultHost.getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
    },
  };

  const program = ts.createProgram({
    rootNames: Array.from(virtualContents.keys()),
    options: compilerOptions,
    host,
  });

  const diagnostics = ts.getPreEmitDiagnostics(program);
  if (diagnostics.length === 0) {
    return;
  }

  const diagnosticMessages = diagnostics.map((diagnostic) => formatDiagnostic(diagnostic, virtualToGeneratedPath));
  throw new CodeGenError(
    "COMPILE_VALIDATION_FAILED",
    `generated TypeScript did not pass noEmit validation: ${diagnosticMessages.join(" | ")}`,
  );
}

function recoveryForError(code: CodeGenErrorCode): { action: RecoveryAction; rationale: string } {
  if (code === "SCOPE_VIOLATION") {
    return {
      action: "retry_modified",
      rationale: "Generated paths must stay inside outputDir; retry with corrected relative paths.",
    };
  }
  if (code === "COMPILE_VALIDATION_FAILED") {
    return {
      action: "retry_modified",
      rationale: "Generated TypeScript failed validation; retry with compile-safe output.",
    };
  }
  if (code === "INPUT_INVALID") {
    return {
      action: "retry_modified",
      rationale: "Input is missing required generation fields; retry with a valid FileSpec payload.",
    };
  }
  return {
    action: "escalate",
    rationale: "Unexpected generation failure; escalate to operator.",
  };
}

function buildFailureEvent(
  correlationId: string,
  code: CodeGenErrorCode,
  message: string,
  recoveryAction: RecoveryAction,
): EventEnvelope {
  return EventEnvelopeSchema.parse({
    eventName: "code-gen.failed",
    eventVersion: "v1",
    occurredAt: nowIso(),
    correlationId,
    payload: {
      agent: AGENT_NAME,
      error: { code, message },
      recoveryAction,
    },
  });
}

function parseCorrelationId(rawInput: unknown): string {
  if (
    rawInput &&
    typeof rawInput === "object" &&
    typeof (rawInput as { correlationId?: unknown }).correlationId === "string" &&
    (rawInput as { correlationId: string }).correlationId.trim().length > 0
  ) {
    return (rawInput as { correlationId: string }).correlationId.trim();
  }
  return AGENT_NAME;
}

function toCodeGenError(error: unknown): { code: CodeGenErrorCode; message: string } {
  if (error instanceof CodeGenError) {
    return {
      code: error.code,
      message: error.message,
    };
  }
  if (error instanceof Error) {
    return {
      code: "GENERATION_FAILED",
      message: error.message,
    };
  }
  return {
    code: "GENERATION_FAILED",
    message: String(error),
  };
}

async function runImpl(input: CodeGenInput): Promise<CodeGenOutput> {
  const parsed = CodeGenInputSchema.parse(input);
  const generatedFiles = buildGeneratedFiles(parsed);
  validateTypeScriptCompilation(generatedFiles);
  return CodeGenOutputSchema.parse({
    generatedFiles,
    runtimeEvents: [],
  });
}

export async function run(input: CodeGenInput): Promise<AgentResult<CodeGenOutput>> {
  const startedAt = nowIso();
  const startedMs = Date.now();
  const correlationId = parseCorrelationId(input);

  try {
    const data = await runImpl(input);
    const endedMs = Date.now();
    return {
      ok: true,
      agent: AGENT_NAME,
      startedAt,
      finishedAt: nowIso(),
      ms: msBetween(startedMs, endedMs),
      errors: [],
      data,
    };
  } catch (error) {
    const endedMs = Date.now();
    const { code, message } = toCodeGenError(error);
    const recovery = recoveryForError(code);
    const runtimeEvent = buildFailureEvent(correlationId, code, message, recovery.action);
    const failureData = CodeGenOutputSchema.parse({
      generatedFiles: [],
      runtimeEvents: [runtimeEvent],
      recovery,
    });

    return {
      ok: false,
      agent: AGENT_NAME,
      startedAt,
      finishedAt: nowIso(),
      ms: msBetween(startedMs, endedMs),
      errors: [{ code, message }],
      data: failureData,
    };
  }
}
